import styles from "./Privacy.module.scss";
const Page = () => {
  return (
    <div className={styles.container}>
      <h1>Privacy Policy</h1>
      <p>Last updated: June 24, 2023</p>
      <p>
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p>We don’t store personal information on our servers</p>
      <p>
        We don’t share your personal information with anyone except to comply
        with the law, develop our products, or protect our rights. This Privacy
        Policy has been created with the help of the{" "}
        <a
          href="https://www.privacypolicies.com/privacy-policy-generator/"
          target="_blank"
        >
          Privacy Policy Generator
        </a>
        .
      </p>
      <h1>Interpretation and Definitions</h1>
      <h2>Interpretation</h2>
      <p>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>
      <h2>Definitions</h2>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li>
          <p>
            <strong>Company</strong> (referred to as either &quot;the
            Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
            this Agreement) refers to the developer blog.
          </p>
        </li>
        <li>
          <p>
            <strong>Cookies</strong> are small files that are placed on Your
            computer, mobile device or any other device by a website, containing
            the details of Your browsing history on that website among its many
            uses.
          </p>
        </li>
        <li>
          <p>
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cellphone or a digital tablet.
          </p>
        </li>
        <li>
          <p>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </p>
        </li>
        <li>
          <p>
            <strong>Service</strong> refers to the Website.
          </p>
        </li>
        <li>
          <p>
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Service, to provide the Service on behalf of the
            Company, to perform services related to the Service or to assist the
            Company in analyzing how the Service is used.
          </p>
        </li>
        <li>
          <p>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </p>
        </li>
        <li>
          <p>
            <strong>Website</strong> refers to the developer blog, accessible
            from{" "}
            <a
              href="https://thedeveloperblog.vercel.app/"
              rel="external nofollow noopener"
              target="_blank"
            >
              https://thedeveloperblog.vercel.app/
            </a>
          </p>
        </li>
        <li>
          <p>
            <strong>You</strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </p>
        </li>
      </ul>
      <h1>Collecting and Using Your Personal Data</h1>
      <h2>Types of Data Collected</h2>
      <h3>Personal Data</h3>
      <p>
        While using Our Service, We may ask You to optionally provide Us with
        certain personally identifiable information that can be used to contact
        only when needed or when you leave a comment. Personally identifiable
        information may include:
      </p>
      <ul>
        <li>
          <p>Email address</p>
        </li>
        <li>
          <p>Names</p>
        </li>
        <li>
          <p>Usage Data</p>
        </li>
      </ul>
      <h1>Usage Data</h1>
      <p>Usage Data is collected automatically when using the Service.</p>
      <p>
        Usage Data may include information such as Your Device's Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data. These are automatically collect by the use of analytics
        tools such as google analytics.
      </p>
      <p>
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, the IP address of Your mobile
        device, Your mobile operating system, the type of mobile Internet
        browser You use. These are also automatically collect by analytics
        tools.
      </p>
      <h1>Comments</h1>
      <p>
        When visitors leave comments on the site we collect the data shown in
        the comments form, this information includes names that you wish to be
        displayed along the comment, email for contacting incase you wish to
        remove the comment and the comment it&apos;s self.
      </p>
      <h1>Cookies</h1>
      <p>
        We do use any Cookies except ones set automatically by analytic tools
        such as google analytics to store and count page views, calculate
        visitor, session and campaign data and track site usage for the site's
        analytics report. The cookie stores information anonymously and assigns
        a randomly generated number to recognise unique visitors.
      </p>
      <h2>Use of Your Data</h2>
      <p>The Company may use Data for the following purposes:</p>
      <ul>
        <li>
          <p>
            <strong>To provide and maintain our Service:</strong>, including to
            monitor the usage of our Service.
          </p>
        </li>
        <li>
          <p>
            <strong>To contact You:</strong> To contact You by email, regarding
            updates or informative communications related to the functionalities
            or products when necessary or reasonable for their implementation.
          </p>
        </li>
        <li>
          <p>
            <strong>To provide You</strong> with news, updates and general
            information about other goods.
          </p>
        </li>
        <li>
          <p>
            <strong>To manage Your requests:</strong> To attend and manage Your
            requests to Us.
          </p>
        </li>
      </ul>
      <h2>Retention of Your Personal Data</h2>
      <p>
        We will retain Usage Data for internal analysis purposes. Usage Data is
        generally retained for a shorter period of time, except when this data
        is used to strengthen the security or to improve the functionality of
        Our Service, or We are legally obligated to retain this data for longer
        time periods.
      </p>
      <h2>Delete Your Personal Data</h2>
      <p>
        You have the right to request that We assist you in deleting the
        Personal Data that We have collected about You. These may include
        comments, emails and names.
      </p>
      <h2>Disclosure of Your Personal Data</h2>
      <h3>Law enforcement</h3>
      <p>
        Under certain circumstances, the Company may be required to disclose
        Your Personal Data if required to do so by law or in response to valid
        requests by public authorities (e.g. a court or a government agency).
      </p>
      <h3>Other legal requirements</h3>
      <p>
        The Company may disclose Your Personal Data in the good faith belief
        that such action is necessary to:
      </p>
      <ul>
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>
          Prevent or investigate possible wrongdoing in connection with the
          Service
        </li>
        <li>
          Protect the personal safety of Users of the Service or the public
        </li>
        <li>Protect against legal liability</li>
      </ul>
      <h1>Links to Other Websites</h1>
      <p>
        Our Service may contain links to other websites that are not operated by
        Us. If You click on a third party link, You will be directed to that
        third party's site. We strongly advise You to review the Privacy Policy
        of every site You visit.
      </p>
      <p>
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </p>
      <h1>Changes to this Privacy Policy</h1>
      <p>
        We may update Our Privacy Policy from time to time. We will notify You
        of any changes by posting the new Privacy Policy on this page.
      </p>
      <p>
        We will let You know via email and/or a prominent notice on Our Service,
        prior to the change becoming effective and update the &quot;Last
        updated&quot; date at the top of this Privacy Policy.
      </p>
      <p>
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>
      <h1>Contact Us</h1>
      <p>
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <ul>
        <li>
          <p>By email: thedeveloperbl0og@gmail.com</p>
        </li>
        <li>
          <p>
            By visiting the contact section on our website down below or by
            clicking: <a href="#contact">here</a>
          </p>
        </li>
      </ul>
    </div>
  );
};

export default Page;
