export const metadata = {
  title: "The Developer Blog",
  description: "Generated by Next.js",
};
import "../styles/globals.css";
import Footer from "@/components/Footer/Footer";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
